<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>8 August</title>
</head>

<body>


    <script>
        // let promise1 = new Promise(function (resolve, reject) {
        //     let arr = [10, 20, 30, 40, 50, 60];
        //     let b = arr.find(value => value == 50);
        //     if (b) {
        //         resolve(b);
        //     } else {
        //         reject("ERROR: Invalid");
        //     }
        // });
        // promise1.then(function (value) {
        //     console.log(value);
        // }).catch(function (value) {
        //     console.log(value);
        // });

        // let promise2 = new Promise(function (resolve, reject) {
        //     let arr1 = [10, 20, 30, 40, 50, 60];
        //     let arr2 = [10, 20, 30, 40, 50, 60];
        //     let b = arr1.find(value => value == 30);
        //     let c = arr2.find(value => value == 70);
        //     if (b && c) {
        //         resolve("Both are True");
        //     } else if (b || c) {
        //         resolve("Only one True");
        //     } else {
        //         reject("ERROR: Both are False");
        //     }
        // });
        // promise2.then(function (value) {
        //     console.log(value);
        // }).catch(function (value) {
        //     console.log(value);              // Use to Handle Errors
        // });

        // async function myFunction() {
        //     return "Hello, world!";
        // }
        // console.log(myFunction());


        // async function normalFunction() {           // Normal function
        //     return "Hello, world!";
        // }
        // normalFunction().then((value) => console.log(value));

        // let differentStyle = async function () {
        //     return "Hello, world!";
        // }
        // differentStyle().then((value) => console.log(value));

        // let arrowFunction = async () => "Hello, world!";     // Arrow function
        // arrowFunction().then((value) => console.log(value));


        // async function test() {
        //     console.log(2);
        //     await console.log(3);
        //     console.log(4);
        // }
        // console.log(1);
        // test();
        // console.log(5);

        // async function myData() {
        //     let a = [1, 2, 3, 4];
        //     return ab;
        // }
        // myData().then((value) => console.log(value)).catch((err) => console.log("ERROR: " + err.message));

        // With try and catch method we can not add catch message in all time when we invoked the function
        // async function myData() {
        //     try {
        //         let a = [1, 2, 3, 4];
        //         return a;                   // Here , print a array when the function is invoked.
        //         // return ab;               // Here , gives an error so print catch.
        //     } catch (e) {
        //         console.log("ERROR: " + e.message);     // Print Error message
        //     }
        // }
        // myData().then((value) => console.log(value));

        // async function myFunction() {
        //     let promise3 = new Promise(function (resolve, reject) {
        //         setTimeout(() => {
        //             resolve(10);
        //         }, 1000);
        //     });
        //     let promise4 = new Promise(function (resolve, reject) {
        //         setTimeout(() => {
        //             resolve(20);
        //         }, 2000);
        //     });
        //     let b = await promise4;
        //     let c = await promise3;
        //     return [b, c];
        // }
        // myFunction().then(value => console.log(value));

        // async function myFunction() {
        //     try {
        //         console.log("The Promise is resolved!");
        //     } catch (error) {
        //         console.error("The Promise is rejected!");
        //     } finally {
        //         console.log(
        //             "The Promise is settled, meaning it has been resolved or rejected."
        //         );
        //     }
        // }
        // myFunction()


        // async function myFunction() {
        //     let arr1 = [1, 2, 3, 4];
        //     let arr2 = [5, 6, 7, 8];
        //     let arr3 = [9, 10, 11, 12];
        //     let pro1 = new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             resolve(arr1);
        //         }, 2000);
        //     });
        //     let pro2 = new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             resolve(arr2);
        //         }, 4000);
        //     });
        //     let pro3 = new Promise((resolve, reject) => {
        //         resolve(arr3);
        //     });
        //     // console.log("We are waiting for Promise 1 to resolve");
        //     // let a = await pro1;
        //     // console.log(a);
        //     // console.log("We are waiting for Promise 2 to resolve");
        //     let b = await pro2;
        //     // console.log(b);
        //     // console.log("This is Promise 3 ");
        //     // let c = await pro3; //  We can not set the timeout here because pro3 is waiting for pro1 and pro2 to resolve
        //     // console.log(c);
        //     // return [a, b, c];
        //     pro1.then(value => console.log(value));
        //     pro2.then(value => console.log(value));
        //     pro3.then(value => console.log(value));
        // };
        // myFunction();

        // console.log(Promise.resolve("Promise Resolved"));
        // console.log(Promise.reject("Promise Rejected"));

        // console.log("STARTING");
        // let pro = new Promise((resolve, reject) => {
        //     resolve("Promise Resolved");
        // });
        // pro.then((res) => { console.log(res); });
        // console.log("STOP");


        function first() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(`Promise Resolved First`);
                }, 1000);
            });
        }
        function second() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(`Promise Resolved Second`);
                }, 1000);
            });
        }
        function third() {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve(`Promise Resolved Third`);
                }, 1000);
            });
        }
        // console.log(first());                    // Doubt

        // // first()
        // //     .then(value => {
        // //         console.log(value);
        // //         second().then(value => {
        // //             console.log(value);
        // //             third().then(value => { console.log(value); });
        // //         });
        // //     })
        // //     .catch(err => console.log("ERROR", err.message));

        // // This is more readable than above code
        // first().then(value => {
        //     console.log(value);
        //     return second();            // Retuen a new Promise and use another then to get the value of the new promises
        // }).then(value => {
        //     console.log(value);
        //     return third();             // Same as above
        // }).then(value => {
        //     console.log(value);
        // }).catch(err => console.log("ERROR", err.message));

        // Print all the promises in one functions 
        // function printAllFunction(array) {
        //     if (array.length == 0) { return }
        //     let storeVar = array.shift();
        //     storeVar.then(value => {
        //         console.log(value);
        //     }).catch(err => console.log("ERROR"));
        //     printAllFunction(array);
        // }
        // printAllFunction([
        //     first(),
        //     second(),
        //     third()
        // ])

        // Promise Combinator
        // ----------------------------Promise.all();----------------------------
        // Promise.all([
        //     first(),
        //     second(),
        //     third()
        // ]).then(value => { console.log(value); }).catch(err => console.log("ERROR"));

        // ----------------------------Promise.race();----------------------------
        // In Promise.race it will return a first promise which will be return first not metter it will resolve or reject.
        // Promise.race([
        //     first(),
        //     second(),
        //     third()
        // ]).then(value => { console.log(value); }).catch(err => console.log("ERROR"));

        // ----------------------------Promise.race();----------------------------
        // In Promise.allSettled it will retuen array of object and return all promises if anyone is rejected it will not gives an error
        // Promise.allSettled([
        //     first(),
        //     second(),
        //     third()
        // ]).then(value => { console.log(value); }).catch(err => console.log("ERROR"));

        // ----------------------------Promise.race();----------------------------
        // In Promise.any first resolved promise will be returned If all promises are reject then the catch method will be called.
        // Promise.any([
        //     first(),
        //     second(),
        //     third()
        // ]).then(value => { console.log(value); }).catch(err => console.log("ERROR"));

        // async function result() {
        //     try {
        //         let pro1 = await first();
        //         console.log(pro1);
        //         let pro2 = await second();
        //         console.log(pro2);
        //         let pro3 = await third();
        //         console.log(pro3);
        //     } catch (error) {
        //         console.log("ERROR");
        //     }
        // }
        // result();

        // console.log("STARTING");
        // let promise = new Promise((resolve, reject) => {
        //     console.log(1);
        //     resolve(2);
        //     console.log(3);
        // });
        // promise.then(result => console.log(result));
        // console.log("ENDING");

        // console.log("STARTING");
        // function func() {
        //     return new Promise((resolve, reject) =>{
        //         console.log(1);
        //         resolve("Resolved");
        //     });
        // }
        // console.log("WORKING");
        // func().then(result => console.log(result));
        // console.log("ENDING");


        // let pro = new Promise((resolve, reject) => {
        //     reject();
        // });
        // pro
        //     .then(() => console.log("SUCCESSFUL - 1"))
        //     .then(() => console.log("SUCCESSFUL -2"))
        //     .then(() => console.log("SUCCESSFUL - 3"))           // Doubt
        //     .catch(() => console.log("ERROR"))
        //     .then(() => console.log("SUCCESSFUL - 4"))
        //     .then(() => console.log("SUCCESSFUL - 5"))

        function hello(para) {
            return new Promise((resolve, reject) => {
                if (para) {
                    resolve("Resolved successfully");
                } else {
                    reject("Rejected");
                }
            });
        }
        // hello(true)
        //     .then(value => {
        //         console.log(value);
        //         return hello(false);
        //     }).catch(err => {
        //         console.log(err);
        //         return "Hello World!";
        //     }).then(value => {
        //         console.log(value);
        //         return hello(true);
        //     }).catch(err => {
        //         console.log(err);
        //     });

        // console.log(hello(false).then(value => console.log(value)).catch(err => console.log("ERROR")).then(arr=>console.log(arr)));
        // console.log(hello(false).catch(value => {
        //     console.log(value);
        //     return "Hello";
        // }).then(() => console.log("HELLO")))

        // let promise1 = new Promise((resolve, reject) => {
        //     resolve("Resolved successfully")
        // });
        // let promise2 = new Promise((resolve, reject) => {
        //     resolve(promise1)
        // });

        // promise1.then((value) => value).then((value) => console.log(value));

        // let promise9 = new Promise((resolve, reject) => {
        //     let random = Math.random();
        //     if (random > 0.5) {
        //         resolve(random);
        //     } else {
        //         reject("ERROR");
        //     }
        // });

        // promise9
        //     .then(value => {
        //         console.log('Resolved:' + value);
        //     })
        //     .catch(error => {
        //         console.error(error);
        //     });

        // function getData() {
        //     return new Promise((resolve, reject) => {
        //         setTimeout(() => {
        //             resolve("Resolved");                        // Doubt
        //         }, 1000);
        //     });
        // }
        // async function first() {
        //     let res = getData();
        //     console.log(res);
        // }
        // first();
        // async function mainResult() {
        //     let res = await getData();
        //     console.log(res);
        // }
        // mainResult();

        // function getNumber(input) {
        //     return new Promise(resolve => {
        //         setTimeout(() => {
        //             resolve(input)
        //         }, 1000);
        //     });
        // }
        // function multiplyByTwo(num) {
        //     return new Promise(resolve => {
        //         setTimeout(() => {
        //             resolve(num * 2)
        //         }, 1000);
        //     });
        // }
        // getNumber(10)
        //     .then(num => {
        //         console.log('The Number Is :-', num);
        //         return multiplyByTwo(num);
        //     })
        //     .then(res => {
        //         console.log('Number Multiply By Two is :-', res);
        //     })
        //     .catch(error => {
        //         console.error('ERROR');
        //     });


        // const promise1 = Promise.reject(10);
        // const promise2 = new Promise((resolve, reject) => {
        //     setTimeout(() => {
        //         resolve(20);
        //     }, 1000);
        // });
        // Promise.any([promise1, promise2])
        //     .then(values => {
        //         console.log(values);
        //     })
        //     .catch(error => {
        //         console.error("ERROR");
        //     });

        // let promise = new Promise((resolve, reject) => { reject(); });
        // promise
        //     .then(value => console.log(value))
        //     .catch(error => {
        //         console.log("ERROR");
        //         return "Hello, world!";
        //     })
        //     .then(value => console.log(value));



    </script>
</body>

</html>